---
- name: Display the kubeadm join command for each node
  debug:
    msg: "{{ hostvars[item]['kubernetes_join_command'] }}"
  with_items: "{{ groups['kube-node'] }}"
  when: "hostvars[item]['kubernetes_join_command'] is defined"

- name: Join node to Kubernetes control plane.
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
