---
- name: Join node to Kubernetes control plane.
  command: >
    {{ kubernetes_join_command }}  --cri-socket {{ kubernetes.init_configuration.nodeRegistration.criSocket }}
    creates=/etc/kubernetes/kubelet.conf
