# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gutehall/ubuntu24-04"
  config.vm.box_version = "2024.08.30"
  config.vm.provider 'virtualbox' do |v|
    v.cpus = 2
    v.memory = 2048
  end
  # config.vm.synced_folder "..", "/src", create: true
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_roles_path = "../../"
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end
end

