# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider 'virtualbox' do |v|
    v.cpus = 2
    v.memory = 2048
  end
  # config.vm.synced_folder "..", "/src", create: true
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yaml"
    ansible.galaxy_roles_path = "./roles"
  end
end

